import { Metadata } from 'next';
import { EnhancedToolLayout } from '@/components/tools/EnhancedToolLayout';
import { TrustCalculator } from '@/components/converters/finance/TrustCalculator';

export const metadata: Metadata = {
  title: 'Trust Calculator - Calculate Trust Distributions & Tax Benefits | InterConverter',
  description: 'Calculate trust distributions and tax benefits with our free trust calculator. Plan estate distributions and optimize tax strategies.',
  keywords: ['trust calculator', 'trust distributions', 'tax benefits', 'estate planning', 'trust tax'],
  openGraph: {
    title: 'Trust Calculator - Calculate Trust Distributions & Tax Benefits',
    description: 'Calculate trust distributions and tax benefits with our free trust calculator.',
    type: 'website',
  },
};

const toolConfig = {
  title: 'Trust Calculator',
  description: 'Calculate trust distributions and tax benefits for estate planning',
  features: [
    'Calculate trust distributions',
    'Tax benefit analysis',
    'Income vs principal distributions',
    'Beneficiary tax implications',
    'Estate planning optimization'
  ],
  usageGuide: [
    'Enter trust principal amount',
    'Specify annual income generated',
    'Set distribution percentage',
    'Review tax implications',
    'Optimize distribution strategy'
  ],
  faqs: [
    {
      question: 'What is a trust distribution?',
      answer: 'A trust distribution is money or property paid out from a trust to its beneficiaries. Distributions can be from income generated by trust assets or from the principal itself.'
    },
    {
      question: 'How are trust distributions taxed?',
      answer: 'Income distributions are generally taxable to beneficiaries, while principal distributions are typically not taxable. The trust may pay taxes on undistributed income.'
    },
    {
      question: 'What is the difference between income and principal distributions?',
      answer: 'Income distributions come from earnings generated by trust assets (dividends, interest, rent), while principal distributions reduce the trust\'s original assets.'
    }
  ]
};

export default function TrustCalculatorPage() {
  return (
    <EnhancedToolLayout
      title={toolConfig.title}
      description={toolConfig.description}
      customFeatures={toolConfig.features}
      customHowToUse={toolConfig.usageGuide}
      faqs={toolConfig.faqs}
      toolId="trust-calculator"
      category="finance"
    >
      <TrustCalculator />
    </EnhancedToolLayout>
  );
}
