name = "InterConverter"
compatibility_date = "2025-08-14"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "InterConverter"

[env.preview]
name = "InterConverterPreview"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"
